import 'dotenv/config';
import { games } from './schema';
import { db } from '@/shared/database/db';

const gamesInitial = [
  {
    id: 516,
    title: 'PUBG: BATTLEGROUNDS',
    thumbnail: 'https://www.freetogame.com/g/516/thumbnail.jpg',
    short_description:
      'Get into the action in one of the longest running battle royale games PUBG Battlegrounds.',
    game_url: 'https://www.freetogame.com/open/pubg',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'KRAFTON, Inc.',
    developer: 'KRAFTON, Inc.',
    release_date: '2022-01-12',
    freetogame_profile_url: 'https://www.freetogame.com/pubg',
  },
  {
    id: 508,
    title: 'Enlisted',
    thumbnail: 'https://www.freetogame.com/g/508/thumbnail.jpg',
    short_description:
      'Get ready to command your own World War II military squad in Gaijin and Darkflow Software’s MMO squad-based shooter Enlisted. ',
    game_url: 'https://www.freetogame.com/open/enlisted',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Gaijin Entertainment',
    developer: 'Darkflow Software',
    release_date: '2021-04-08',
    freetogame_profile_url: 'https://www.freetogame.com/enlisted',
  },
  {
    id: 644,
    title: 'World of Tanks: HEAT',
    thumbnail: 'https://www.freetogame.com/g/644/thumbnail.jpg',
    short_description:
      'A free-to-play hero-based shooter set in the World of Tanks universe.',
    game_url: 'https://www.freetogame.com/open/world-of-tanks-heat',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Wargaming Group Limited',
    developer: 'Wargaming Group Limited',
    release_date: '2026-05-26',
    freetogame_profile_url: 'https://www.freetogame.com/world-of-tanks-heat',
  },
  {
    id: 642,
    title: 'Neverness to Everness',
    thumbnail: 'https://www.freetogame.com/g/642/thumbnail.jpg',
    short_description:
      'Neverness to Everness is a gacha game that blends some GTA-style play with team-based combat.',
    game_url: 'https://www.freetogame.com/open/nte',
    genre: 'RPG',
    platform: 'PC (Windows)',
    publisher: 'Perfect World Entertainment',
    developer: 'Hotta Studio',
    release_date: '2026-04-29',
    freetogame_profile_url: 'https://www.freetogame.com/nte',
  },
  {
    id: 590,
    title: 'Throne And Liberty',
    thumbnail: 'https://www.freetogame.com/g/590/thumbnail.jpg',
    short_description:
      'A free-to-play multi-platorm MMORPG from NCSoft and Amazon Games.',
    game_url: 'https://www.freetogame.com/open/throne-and-liberty',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'Amazon Games',
    developer: 'NCSoft',
    release_date: '2024-10-01',
    freetogame_profile_url: 'https://www.freetogame.com/throne-and-liberty',
  },
  {
    id: 523,
    title: 'Fall Guys',
    thumbnail: 'https://www.freetogame.com/g/523/thumbnail.jpg',
    short_description:
      'Play the most competitive massively multiplayer party royale game featuring beans ever for free on a variety of platforms. ',
    game_url: 'https://www.freetogame.com/open/fall-guys',
    genre: 'Battle Royale',
    platform: 'PC (Windows)',
    publisher: 'Mediatonic',
    developer: 'Mediatonic',
    release_date: '2020-08-04',
    freetogame_profile_url: 'https://www.freetogame.com/fall-guys',
  },
  {
    id: 11,
    title: 'Neverwinter',
    thumbnail: 'https://www.freetogame.com/g/11/thumbnail.jpg',
    short_description:
      'A free-to-play 3D action MMORPG based on the acclaimed Dungeons & Dragons fantasy roleplaying game. ',
    game_url: 'https://www.freetogame.com/open/neverwinter',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'Perfect World Entertainment',
    developer: 'Cryptic Studios',
    release_date: '2013-12-06',
    freetogame_profile_url: 'https://www.freetogame.com/neverwinter',
  },
  {
    id: 517,
    title: 'Lost Ark',
    thumbnail: 'https://www.freetogame.com/g/517/thumbnail.jpg',
    short_description:
      'Smilegate’s free-to-play multiplayer ARPG is a massive adventure filled with lands waiting to be explored, people waiting to be met, and an ancient evil waiting to be destroyed.',
    game_url: 'https://www.freetogame.com/open/lost-ark',
    genre: 'ARPG',
    platform: 'PC (Windows)',
    publisher: 'Amazon Games',
    developer: 'Smilegate RPG',
    release_date: '2022-02-11',
    freetogame_profile_url: 'https://www.freetogame.com/lost-ark',
  },
  {
    id: 475,
    title: 'Genshin Impact',
    thumbnail: 'https://www.freetogame.com/g/475/thumbnail.jpg',
    short_description:
      'If you’ve been looking for a game to scratch that open-world action RPG itch, one with perhaps a bit of Asian flair, then you’re going to want to check out miHoYo’s Genshin Impact.',
    game_url: 'https://www.freetogame.com/open/genshin-impact',
    genre: 'Action RPG',
    platform: 'PC (Windows)',
    publisher: 'miHoYo',
    developer: 'miHoYo',
    release_date: '2020-09-28',
    freetogame_profile_url: 'https://www.freetogame.com/genshin-impact',
  },
  {
    id: 9,
    title: 'World of Warships',
    thumbnail: 'https://www.freetogame.com/g/9/thumbnail.jpg',
    short_description:
      'A 3D free to play naval action-themed MMO from the creators of World of Tanks! ',
    game_url: 'https://www.freetogame.com/open/world-of-warships',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Wargaming',
    developer: 'Wargaming',
    release_date: '2015-07-02',
    freetogame_profile_url: 'https://www.freetogame.com/world-of-warships',
  },
  {
    id: 2,
    title: 'World of Tanks',
    thumbnail: 'https://www.freetogame.com/g/2/thumbnail2.jpg',
    short_description:
      'If you like blowing up tanks, with a quick and intense game style you will love this game!',
    game_url: 'https://www.freetogame.com/open/world-of-tanks',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Wargaming',
    developer: 'Wargaming',
    release_date: '2011-04-12',
    freetogame_profile_url: 'https://www.freetogame.com/world-of-tanks',
  },
  {
    id: 628,
    title: 'World of Sea Battle',
    thumbnail: 'https://www.freetogame.com/g/628/thumbnail.jpg',
    short_description: 'A free-to-play historical open-sea MMORPG.',
    game_url: 'https://www.freetogame.com/open/world-of-sea-battle',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'Thera Interactive',
    developer: 'Thera Interactive',
    release_date: '2025-10-21',
    freetogame_profile_url: 'https://www.freetogame.com/world-of-sea-battle',
  },
  {
    id: 521,
    title: 'Diablo Immortal',
    thumbnail: 'https://www.freetogame.com/g/521/thumbnail.jpg',
    short_description:
      'Built for mobile and also released on PC, Diablo Immortal fills in the gaps between Diablo II and III in an MMOARPG environment.',
    game_url: 'https://www.freetogame.com/open/diablo-immortal',
    genre: 'MMOARPG',
    platform: 'PC (Windows)',
    publisher: 'Blizzard Entertainment',
    developer: 'Blizzard Entertainment',
    release_date: '2022-06-02',
    freetogame_profile_url: 'https://www.freetogame.com/diablo-immortal',
  },
  {
    id: 511,
    title: 'Phantasy Star Online 2 New Genesis',
    thumbnail: 'https://www.freetogame.com/g/511/thumbnail.jpg',
    short_description:
      'The legacy of Phantasy Star Online 2 continues a thousand years later!',
    game_url: 'https://www.freetogame.com/open/pso2-new-genesis',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'Sega',
    developer: 'Sega',
    release_date: '2021-06-09',
    freetogame_profile_url: 'https://www.freetogame.com/pso2-new-genesis',
  },
  {
    id: 5,
    title: 'Crossout',
    thumbnail: 'https://www.freetogame.com/g/5/thumbnail.jpg',
    short_description: 'A post-apocalyptic MMO vehicle combat game! ',
    game_url: 'https://www.freetogame.com/open/crossout',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Targem',
    developer: 'Gaijin',
    release_date: '2017-05-30',
    freetogame_profile_url: 'https://www.freetogame.com/crossout',
  },
  {
    id: 12,
    title: 'War Thunder',
    thumbnail: 'https://www.freetogame.com/g/12/thumbnail.jpg',
    short_description:
      'A MMO shooter that puts you in command of hundreds of the finest combat vehicles of World War II.',
    game_url: 'https://www.freetogame.com/open/war-thunder',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Gaijin Entertainment',
    developer: 'Gaijin Entertainment',
    release_date: '2013-08-15',
    freetogame_profile_url: 'https://www.freetogame.com/war-thunder',
  },
  {
    id: 648,
    title: 'Ragnarok: The New World',
    thumbnail: 'https://www.freetogame.com/g/648/thumbnail.jpg',
    short_description: 'An open-world entry in the Ragnarok IP.',
    game_url: 'https://www.freetogame.com/open/ragnarok-the-new-world',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'Gravity Game Vision Limited',
    developer: 'Gravity Game Vision Limited',
    release_date: '2026-07-27',
    freetogame_profile_url: 'https://www.freetogame.com/ragnarok-the-new-world',
  },
  {
    id: 624,
    title: 'Battlefield REDSEC',
    thumbnail: 'https://www.freetogame.com/g/624/thumbnail.jpg',
    short_description:
      'A free-to-play battle royale game built with Battlefield DNA.',
    game_url: 'https://www.freetogame.com/open/battlefield-redsec',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Electronic Arts',
    developer: 'Battlefield Studios',
    release_date: '2025-10-28',
    freetogame_profile_url: 'https://www.freetogame.com/battlefield-redsec',
  },
  {
    id: 641,
    title: 'Foundation: Galactic Frontier',
    thumbnail: 'https://www.freetogame.com/g/641/thumbnail.jpg',
    short_description:
      'Isaac Asimov’s series brought to life in a massive real-time strategy RPG featuring crew management and galactic warfare.',
    game_url: 'https://www.freetogame.com/open/foundation-galactic-frontier',
    genre: 'Strategy',
    platform: 'PC (Windows)',
    publisher: 'FunPlus International',
    developer: 'FunPlus International',
    release_date: '2025-10-21',
    freetogame_profile_url:
      'https://www.freetogame.com/foundation-galactic-frontier',
  },
  {
    id: 599,
    title: 'Marvel Rivals',
    thumbnail: 'https://www.freetogame.com/g/599/thumbnail.jpg',
    short_description: 'A free-to-play superhero team shooter from NetEase.',
    game_url: 'https://www.freetogame.com/open/marvel-rivals',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'NetEase',
    developer: 'NetEase',
    release_date: '2024-12-06',
    freetogame_profile_url: 'https://www.freetogame.com/marvel-rivals',
  },
  {
    id: 640,
    title: 'Project Entropy',
    thumbnail: 'https://www.freetogame.com/g/640/thumbnail.jpg',
    short_description:
      'Project Entropy drops you into a living sci-fi MMO universe!',
    game_url: 'https://www.freetogame.com/open/project-entropy',
    genre: 'Strategy',
    platform: 'PC (Windows)',
    publisher: 'FunPlus International',
    developer: 'FunPlus International',
    release_date: '2024-04-17',
    freetogame_profile_url: 'https://www.freetogame.com/project-entropy',
  },
  {
    id: 560,
    title: 'Palia',
    thumbnail: 'https://www.freetogame.com/g/560/thumbnail.jpg',
    short_description: 'A cozy MMO with homebuilding and some adventure.',
    game_url: 'https://www.freetogame.com/open/palia',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'Singularity Six',
    developer: 'Singularity Six',
    release_date: '2023-08-10',
    freetogame_profile_url: 'https://www.freetogame.com/palia',
  },
  {
    id: 14,
    title: 'Star Trek Online',
    thumbnail: 'https://www.freetogame.com/g/14/thumbnail.jpg',
    short_description:
      'A free-to-play, 3D, Sci-Fi MMORPG based on the popular Star Trek series.',
    game_url: 'https://www.freetogame.com/open/star-trek-online',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'Perfect World Entertainment',
    developer: ' Cryptic Studios',
    release_date: '2010-02-02',
    freetogame_profile_url: 'https://www.freetogame.com/star-trek-online',
  },
  {
    id: 626,
    title: 'Where Winds Meet',
    thumbnail: 'https://www.freetogame.com/g/626/thumbnail.jpg',
    short_description:
      'A free-to-play open-world ARPG set in tenth-century China.',
    game_url: 'https://www.freetogame.com/open/where-winds-meet',
    genre: 'RPG',
    platform: 'PC (Windows)',
    publisher: 'Everstone Studio',
    developer: 'NetEase Games',
    release_date: '2025-11-14',
    freetogame_profile_url: 'https://www.freetogame.com/where-winds-meet',
  },
  {
    id: 595,
    title: 'Brighter Shores',
    thumbnail: 'https://www.freetogame.com/g/595/thumbnail.jpg',
    short_description:
      "A point-and-click MMORPG from RuneScape's creator, Andrew Gower.",
    game_url: 'https://www.freetogame.com/open/brighter-shores',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'Fen Research LTD',
    developer: 'Fen Research LTD',
    release_date: '2024-11-06',
    freetogame_profile_url: 'https://www.freetogame.com/brighter-shores',
  },
  {
    id: 515,
    title: 'Halo Infinite',
    thumbnail: 'https://www.freetogame.com/g/515/thumbnail.jpg',
    short_description:
      'For the first time ever, a free-to-play Halo experience is available in the form of Halo Infinite’s multiplayer.',
    game_url: 'https://www.freetogame.com/open/halo-infinite',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Xbox Game Studios',
    developer: '343 Industries',
    release_date: '2021-11-15',
    freetogame_profile_url: 'https://www.freetogame.com/halo-infinite',
  },
  {
    id: 466,
    title: 'Valorant',
    thumbnail: 'https://www.freetogame.com/g/466/thumbnail.jpg',
    short_description:
      'Test your mettle in Riot Games’ character-based FPS shooter Valorant.',
    game_url: 'https://www.freetogame.com/open/valorant',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Riot Games',
    developer: 'Riot Games',
    release_date: '2020-06-02',
    freetogame_profile_url: 'https://www.freetogame.com/valorant',
  },
  {
    id: 467,
    title: 'Phantasy Star Online 2',
    thumbnail: 'https://www.freetogame.com/g/467/thumbnail.jpg',
    short_description:
      'Welcome to ARKS, and elite task force searching dangerous planets for the corrupted Falspawn in Phantasy Star 2 Online, Sega’s popular, free-to-play sci-fi MMORPG.',
    game_url: 'https://www.freetogame.com/open/pso2',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'SEGA',
    developer: 'SEGA',
    release_date: '2020-05-27',
    freetogame_profile_url: 'https://www.freetogame.com/pso2',
  },
  {
    id: 452,
    title: 'Call of Duty: Warzone',
    thumbnail: 'https://www.freetogame.com/g/452/thumbnail.jpg',
    short_description:
      'A standalone free-to-play battle royale and modes accessible via Call of Duty: Modern Warfare.',
    game_url: 'https://www.freetogame.com/open/call-of-duty-warzone',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Activision',
    developer: 'Infinity Ward',
    release_date: '2020-03-10',
    freetogame_profile_url: 'https://www.freetogame.com/call-of-duty-warzone',
  },
  {
    id: 21,
    title: 'Destiny 2',
    thumbnail: 'https://www.freetogame.com/g/21/thumbnail.jpg',
    short_description: 'A free-to-play multiplayer Sci-Fi MMOFPS from Bungie.',
    game_url: 'https://www.freetogame.com/open/destiny-2',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Bungie',
    developer: 'Bungie',
    release_date: '2019-10-01',
    freetogame_profile_url: 'https://www.freetogame.com/destiny-2',
  },
  {
    id: 23,
    title: 'Apex Legends',
    thumbnail: 'https://www.freetogame.com/g/23/thumbnail.jpg',
    short_description:
      'A free-to-play strategic battle royale game featuring 60-player matches and team-based play. ',
    game_url: 'https://www.freetogame.com/open/apex-legends',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Electronic Arts',
    developer: 'Electronic Arts',
    release_date: '2019-02-04',
    freetogame_profile_url: 'https://www.freetogame.com/apex-legends',
  },
  {
    id: 57,
    title: 'Fortnite',
    thumbnail: 'https://www.freetogame.com/g/57/thumbnail.jpg',
    short_description:
      "A free-to-play, standalone mode of Epic Game's Fortnite. ",
    game_url: 'https://www.freetogame.com/open/fortnite-battle-royale',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Epic Games',
    developer: 'Epic Games',
    release_date: '2017-09-26',
    freetogame_profile_url: 'https://www.freetogame.com/fortnite-battle-royale',
  },
  {
    id: 6,
    title: 'Blade and Soul',
    thumbnail: 'https://www.freetogame.com/g/6/thumbnail.jpg',
    short_description:
      'A free-to-play martial arts MMORPG that tasks players with learning combination attacks.',
    game_url: 'https://www.freetogame.com/open/blade-and-soul',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'NCSoft',
    developer: 'NCSoft',
    release_date: '2016-01-19',
    freetogame_profile_url: 'https://www.freetogame.com/blade-and-soul',
  },
  {
    id: 212,
    title: 'Brawlhalla',
    thumbnail: 'https://www.freetogame.com/g/212/thumbnail.jpg',
    short_description:
      'A free-to-play 2D platform fighter inspired by the Smash Bros.',
    game_url: 'https://www.freetogame.com/open/brawlhalla',
    genre: 'Fighting',
    platform: 'PC (Windows)',
    publisher: 'Blue Mammoth Games',
    developer: 'Blue Mammoth Games',
    release_date: '2015-11-03',
    freetogame_profile_url: 'https://www.freetogame.com/brawlhalla',
  },
  {
    id: 8,
    title: 'Trove',
    thumbnail: 'https://www.freetogame.com/g/8/thumbnail.jpg',
    short_description:
      'A free to play Sandbox massively multiplayer online role-playing game! ',
    game_url: 'https://www.freetogame.com/open/trove',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'Trion Worlds',
    developer: 'Trion Worlds',
    release_date: '2015-07-09',
    freetogame_profile_url: 'https://www.freetogame.com/trove',
  },
  {
    id: 13,
    title: 'Guild Wars 2',
    thumbnail: 'https://www.freetogame.com/g/13/thumbnail.jpg',
    short_description:
      "A free-to-play MMORPG, the follow-up to ArenaNet's popular Guild Wars. ",
    game_url: 'https://www.freetogame.com/open/guild-wars-2',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'NCsoft',
    developer: 'ArenaNet',
    release_date: '2012-08-28',
    freetogame_profile_url: 'https://www.freetogame.com/guild-wars-2',
  },
  {
    id: 433,
    title: 'RuneScape',
    thumbnail: 'https://www.freetogame.com/g/433/thumbnail.jpg',
    short_description:
      'A popular 3D browser MMORPG boasting a huge player base and 15 years of content.',
    game_url: 'https://www.freetogame.com/open/runescape',
    genre: 'MMORPG',
    platform: 'PC (Windows), Web Browser',
    publisher: 'Jagex',
    developer: 'Jagex',
    release_date: '2001-01-04',
    freetogame_profile_url: 'https://www.freetogame.com/runescape',
  },
  {
    id: 339,
    title: 'Tibia',
    thumbnail: 'https://www.freetogame.com/g/339/thumbnail.jpg',
    short_description:
      'A old-school free-to-play massively multiplayer online \r\nrole-playing game.',
    game_url: 'https://www.freetogame.com/open/tibia',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'CipSoft',
    developer: 'CipSoft',
    release_date: '1997-01-07',
    freetogame_profile_url: 'https://www.freetogame.com/tibia',
  },
  {
    id: 636,
    title: 'Arknights: Endfield',
    thumbnail: 'https://www.freetogame.com/g/636/thumbnail.jpg',
    short_description: 'A free-to-play RTS RPG gacha game.',
    game_url: 'https://www.freetogame.com/open/arknights-endfield',
    genre: 'Strategy',
    platform: 'PC (Windows)',
    publisher: 'GRYPHLINE',
    developer: 'Hypergryph',
    release_date: '2026-01-21',
    freetogame_profile_url: 'https://www.freetogame.com/arknights-endfield',
  },
  {
    id: 629,
    title: 'Wuthering Waves',
    thumbnail: 'https://www.freetogame.com/g/629/thumbnail.jpg',
    short_description: 'A free-to-play action RPG with gacha elements.',
    game_url: 'https://www.freetogame.com/open/wuthering-waves',
    genre: 'RPG',
    platform: 'PC (Windows)',
    publisher: 'Kuro Games',
    developer: 'Kuro Games',
    release_date: '2024-05-22',
    freetogame_profile_url: 'https://www.freetogame.com/wuthering-waves',
  },
  {
    id: 556,
    title: 'Naraka: Bladepoint',
    thumbnail: 'https://www.freetogame.com/g/556/thumbnail.jpg',
    short_description: 'A free-to-play melee focused battle royale.',
    game_url: 'https://www.freetogame.com/open/naraka-bladepoint',
    genre: 'Battle Royale',
    platform: 'PC (Windows)',
    publisher: '24 Entertainment',
    developer: 'NetEase',
    release_date: '2023-07-13',
    freetogame_profile_url: 'https://www.freetogame.com/naraka-bladepoint',
  },
  {
    id: 605,
    title: 'Honkai: Star Rail',
    thumbnail: 'https://www.freetogame.com/g/605/thumbnail.jpg',
    short_description: 'A free-to-play sci-fantasy game from HoYoVerse',
    game_url: 'https://www.freetogame.com/open/honkai-star-rail',
    genre: 'RPG',
    platform: 'PC (Windows)',
    publisher: 'HoYoVerse',
    developer: 'HoYoVerse',
    release_date: '2023-04-26',
    freetogame_profile_url: 'https://www.freetogame.com/honkai-star-rail',
  },
  {
    id: 649,
    title: "Soul's Remnant",
    thumbnail: 'https://www.freetogame.com/g/649/thumbnail.jpg',
    short_description: 'An indie 2D Side Scroller MMORPG.',
    game_url: 'https://www.freetogame.com/open/souls-remnant',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'Chaomoon',
    developer: 'Chaomoon',
    release_date: '2026-08-13',
    freetogame_profile_url: 'https://www.freetogame.com/souls-remnant',
  },
  {
    id: 646,
    title: 'Gloria Victis',
    thumbnail: 'https://www.freetogame.com/g/646/thumbnail.jpg',
    short_description: 'A free-to-play low-fantasy medieval MMORPG.',
    game_url: 'https://www.freetogame.com/open/gloria-victis',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'Gamigo',
    developer: 'Gamigo',
    release_date: '2026-06-17',
    freetogame_profile_url: 'https://www.freetogame.com/gloria-victis',
  },
  {
    id: 647,
    title: 'RF Online Next',
    thumbnail: 'https://www.freetogame.com/g/647/thumbnail.jpg',
    short_description: 'A free-to-play sci-fi PvP MMORPG.',
    game_url: 'https://www.freetogame.com/open/rf-online-next',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'Netmarble',
    developer: 'Netmarble',
    release_date: '2026-06-15',
    freetogame_profile_url: 'https://www.freetogame.com/rf-online-next',
  },
  {
    id: 643,
    title: 'The Division Resurgence',
    thumbnail: 'https://www.freetogame.com/g/643/thumbnail.jpg',
    short_description:
      'A free-to-play open-world shooter set in The Division universe.',
    game_url: 'https://www.freetogame.com/open/the-division-resurgence',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Ubisoft',
    developer: 'Ubisoft',
    release_date: '2026-04-29',
    freetogame_profile_url:
      'https://www.freetogame.com/the-division-resurgence',
  },
  {
    id: 639,
    title: 'The Seven Deadly Sins: Origin',
    thumbnail: 'https://www.freetogame.com/g/639/thumbnail.jpg',
    short_description:
      'A free-to-play action RPG based on the manga and anime.',
    game_url: 'https://www.freetogame.com/open/the-seven-deadly-sins-origin',
    genre: 'RPG',
    platform: 'PC (Windows)',
    publisher: 'Netmarble',
    developer: 'Netmarble',
    release_date: '2026-03-16',
    freetogame_profile_url:
      'https://www.freetogame.com/the-seven-deadly-sins-origin',
  },
  {
    id: 635,
    title: 'Heartopia',
    thumbnail: 'https://www.freetogame.com/g/635/thumbnail.jpg',
    short_description:
      'A free-to-play life simulation game for multiple players.',
    game_url: 'https://www.freetogame.com/open/heartopia',
    genre: 'Social',
    platform: 'PC (Windows)',
    publisher: 'XD',
    developer: 'XD',
    release_date: '2026-01-16',
    freetogame_profile_url: 'https://www.freetogame.com/heartopia',
  },
  {
    id: 631,
    title: 'Reign of Guilds',
    thumbnail: 'https://www.freetogame.com/g/631/thumbnail.jpg',
    short_description:
      'An open-world MMORPG inspired by old-school games like Ultima Online and EverQuest',
    game_url: 'https://www.freetogame.com/open/reign-of-guilds',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'Atlant Games Ltd',
    developer: 'Atlant Games Ltd',
    release_date: '2025-11-26',
    freetogame_profile_url: 'https://www.freetogame.com/reign-of-guilds',
  },
  {
    id: 621,
    title: '2XKO',
    thumbnail: 'https://www.freetogame.com/g/621/thumbnail.jpg',
    short_description:
      'A free-to-play 2v2 fighting game set in the League of Legends universe.',
    game_url: 'https://www.freetogame.com/open/2xko',
    genre: 'Fighting',
    platform: 'PC (Windows)',
    publisher: 'Riot Games',
    developer: 'Riot Games',
    release_date: '2025-10-07',
    freetogame_profile_url: 'https://www.freetogame.com/2xko',
  },
  {
    id: 622,
    title: 'Blue Protocol: Star Resonance',
    thumbnail: 'https://www.freetogame.com/g/622/thumbnail.jpg',
    short_description: 'A free-to-play open-world anime MMORPG. ',
    game_url: 'https://www.freetogame.com/open/blue-protocol-star-resonance',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'A Plus',
    developer: 'Shanghai Bokura Networkd Technology',
    release_date: '2025-10-09',
    freetogame_profile_url:
      'https://www.freetogame.com/blue-protocol-star-resonance',
  },
  {
    id: 623,
    title: 'Raven2',
    thumbnail: 'https://www.freetogame.com/g/623/thumbnail.jpg',
    short_description: 'A free-to-play open-world MMORPG.',
    game_url: 'https://www.freetogame.com/open/raven2',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'Netmarble',
    developer: 'Netmarble',
    release_date: '2025-10-22',
    freetogame_profile_url: 'https://www.freetogame.com/raven2',
  },
  {
    id: 625,
    title: 'Superball',
    thumbnail: 'https://www.freetogame.com/g/625/thumbnail.jpg',
    short_description: 'A free-to-play futuristic sports game.',
    game_url: 'https://www.freetogame.com/open/superball',
    genre: 'Sports',
    platform: 'PC (Windows)',
    publisher: 'Logoi Games',
    developer: 'Pathea Games',
    release_date: '2025-10-28',
    freetogame_profile_url: 'https://www.freetogame.com/superball',
  },
  {
    id: 615,
    title: 'Arena Breakout: Infinite',
    thumbnail: 'https://www.freetogame.com/g/615/thumbnail.jpg',
    short_description: 'A free-to-play tactical extraction shooter.',
    game_url: 'https://www.freetogame.com/open/arena-breakout-infinite',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'MoreFun Studios',
    developer: 'MoreFun Studios',
    release_date: '2025-09-16',
    freetogame_profile_url:
      'https://www.freetogame.com/arena-breakout-infinite',
  },
  {
    id: 616,
    title: 'Warborne Above Ashes',
    thumbnail: 'https://www.freetogame.com/g/616/thumbnail.jpg',
    short_description: 'A free-to-play PvP-centric MMO.',
    game_url: 'https://www.freetogame.com/open/warborne-above-ashes',
    genre: 'MMO',
    platform: 'PC (Windows)',
    publisher: 'Qooland ',
    developer: 'Qooland',
    release_date: '2025-09-19',
    freetogame_profile_url: 'https://www.freetogame.com/warborne-above-ashes',
  },
  {
    id: 617,
    title: 'Eterspire',
    thumbnail: 'https://www.freetogame.com/g/617/thumbnail.jpg',
    short_description: 'A free-to-play, cross-platform MMORPG.',
    game_url: 'https://www.freetogame.com/open/eterspire',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'Stonehollow Workshop',
    developer: 'Stonehollow Workshop',
    release_date: '2025-09-15',
    freetogame_profile_url: 'https://www.freetogame.com/eterspire',
  },
  {
    id: 618,
    title: 'skate.',
    thumbnail: 'https://www.freetogame.com/g/618/thumbnail.jpg',
    short_description:
      'The latest, free-to-play, entry in the Skate franchise.',
    game_url: 'https://www.freetogame.com/open/skate',
    genre: 'Sports',
    platform: 'PC (Windows)',
    publisher: 'Full Circle',
    developer: 'Electronic Arts',
    release_date: '2025-09-16',
    freetogame_profile_url: 'https://www.freetogame.com/skate',
  },
  {
    id: 619,
    title: 'Blade & Soul Heroes',
    thumbnail: 'https://www.freetogame.com/g/619/thumbnail.jpg',
    short_description:
      'A free-to-play collectible action MMORPG set in the Blade & Soul universe.',
    game_url: 'https://www.freetogame.com/open/blade-soul-heroes',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'NCSoft',
    developer: 'NCSoft',
    release_date: '2025-09-24',
    freetogame_profile_url: 'https://www.freetogame.com/blade-soul-heroes',
  },
  {
    id: 632,
    title: 'Dragon Ball Gekishin Squadra',
    thumbnail: 'https://www.freetogame.com/g/632/thumbnail.jpg',
    short_description:
      'A free-to-play MOBA featuring all your favorite Dragon Ball characters.',
    game_url: 'https://www.freetogame.com/open/dragon-ball-gekishin-squadra',
    genre: 'MOBA',
    platform: 'PC (Windows)',
    publisher: 'Bandai Namco Entertainment',
    developer: 'GANBARION Co., Ltd.',
    release_date: '2025-09-09',
    freetogame_profile_url:
      'https://www.freetogame.com/dragon-ball-gekishin-squadra',
  },
  {
    id: 613,
    title: 'Dfiance',
    thumbnail: 'https://www.freetogame.com/g/613/thumbnail.jpg',
    short_description: 'A free-to-play tactical card game.',
    game_url: 'https://www.freetogame.com/open/dfiance',
    genre: 'Card Game',
    platform: 'PC (Windows)',
    publisher: 'Dfiance',
    developer: 'Dfiance',
    release_date: '2025-08-04',
    freetogame_profile_url: 'https://www.freetogame.com/dfiance',
  },
  {
    id: 614,
    title: 'Dungeon Stalker',
    thumbnail: 'https://www.freetogame.com/g/614/thumbnail.jpg',
    short_description: 'A free-to-play dungeon crawler with survival elements.',
    game_url: 'https://www.freetogame.com/open/dungeon-stalker',
    genre: 'Dungeon Crawler',
    platform: 'PC (Windows)',
    publisher: 'OneUniverse',
    developer: 'OneUniverse',
    release_date: '2025-08-13',
    freetogame_profile_url: 'https://www.freetogame.com/dungeon-stalker',
  },
  {
    id: 611,
    title: 'Mecha BREAK',
    thumbnail: 'https://www.freetogame.com/g/611/thumbnail.jpg',
    short_description: 'A team-based third-person shooter featuring mechs.',
    game_url: 'https://www.freetogame.com/open/mecha-break',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Amazing Seasun Games',
    developer: 'Amazing Seasun Games',
    release_date: '2025-07-01',
    freetogame_profile_url: 'https://www.freetogame.com/mecha-break',
  },
  {
    id: 612,
    title: 'Terminull Brigade',
    thumbnail: 'https://www.freetogame.com/g/612/thumbnail.jpg',
    short_description:
      'A free-to-play third-person looter-shooter with customizable characters.',
    game_url: 'https://www.freetogame.com/open/terminull-brigade',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Pew Pew Games',
    developer: 'Pew Pew Games',
    release_date: '2025-07-29',
    freetogame_profile_url: 'https://www.freetogame.com/terminull-brigade',
  },
  {
    id: 633,
    title: 'Umamusume: Pretty Derby',
    thumbnail: 'https://www.freetogame.com/g/633/thumbnail.jpg',
    short_description:
      'A free-to-play gacha-style sports game featuring racing horse-girls.',
    game_url: 'https://www.freetogame.com/open/umamusume-pretty-derby',
    genre: 'Sports',
    platform: 'PC (Windows)',
    publisher: 'Cygames, Inc.',
    developer: 'Cygames, Inc.',
    release_date: '2025-06-24',
    freetogame_profile_url: 'https://www.freetogame.com/umamusume-pretty-derby',
  },
  {
    id: 609,
    title: 'Crystal Of Atlan',
    thumbnail: 'https://www.freetogame.com/g/609/thumbnail.jpg',
    short_description: 'A magicpunk MMORPG from Nuverse.',
    game_url: 'https://www.freetogame.com/open/crystal-of-atlan',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'Skystone Games',
    developer: 'Nuverse',
    release_date: '2025-05-26',
    freetogame_profile_url: 'https://www.freetogame.com/crystal-of-atlan',
  },
  {
    id: 610,
    title: 'Splitgate: Arena Reloaded',
    thumbnail: 'https://www.freetogame.com/g/610/thumbnail.jpg',
    short_description: 'A free-to-play shooter using portals.',
    game_url: 'https://www.freetogame.com/open/splitgate-arena-reloaded',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: '1047 Games',
    developer: '1047 Games',
    release_date: '2025-05-22',
    freetogame_profile_url:
      'https://www.freetogame.com/splitgate-arena-reloaded',
  },
  {
    id: 606,
    title: 'Steel Hunters',
    thumbnail: 'https://www.freetogame.com/g/606/thumbnail.jpg',
    short_description:
      'A post-apocalyptic extraction shooter with giant mechs.',
    game_url: 'https://www.freetogame.com/open/steel-hunters',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Wargaming ',
    developer: 'Wargaming',
    release_date: '2025-04-02',
    freetogame_profile_url: 'https://www.freetogame.com/steel-hunters',
  },
  {
    id: 607,
    title: 'The Lost Glitches',
    thumbnail: 'https://www.freetogame.com/g/607/thumbnail.jpg',
    short_description: 'A cyberpunk RPG trading card game from Honig Studios.',
    game_url: 'https://www.freetogame.com/open/the-lost-glitches',
    genre: 'Card Game',
    platform: 'PC (Windows)',
    publisher: 'Honig Studios GmbH',
    developer: 'Mimunga LLC',
    release_date: '2025-04-29',
    freetogame_profile_url: 'https://www.freetogame.com/the-lost-glitches',
  },
  {
    id: 608,
    title: 'Odin: Valhalla Rising',
    thumbnail: 'https://www.freetogame.com/g/608/thumbnail.jpg',
    short_description: 'An open-world MMORPG based on Norse mythology.',
    game_url: 'https://www.freetogame.com/open/odin-valhalla-rising',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'Kakao Games',
    developer: 'Lionheart Studios',
    release_date: '2025-04-29',
    freetogame_profile_url: 'https://www.freetogame.com/odin-valhalla-rising',
  },
  {
    id: 603,
    title: 'War Robots: Frontiers',
    thumbnail: 'https://www.freetogame.com/g/603/thumbnail.jpg',
    short_description:
      'A multiplayer mech game set in a planetary system light years from Earth.',
    game_url: 'https://www.freetogame.com/open/war-robots-frontiers',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'My.games',
    developer: 'My.games',
    release_date: '2025-03-04',
    freetogame_profile_url: 'https://www.freetogame.com/war-robots-frontiers',
  },
  {
    id: 604,
    title: 'FragPunk',
    thumbnail: 'https://www.freetogame.com/g/604/thumbnail.jpg',
    short_description:
      'A free-to-play 5v5 hero shooter that uses cards to modify matches.',
    game_url: 'https://www.freetogame.com/open/fragpunk',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Bad Guitar Studio',
    developer: 'Bad Guitar Studio',
    release_date: '2025-03-06',
    freetogame_profile_url: 'https://www.freetogame.com/fragpunk',
  },
  {
    id: 601,
    title: 'Delta Force',
    thumbnail: 'https://www.freetogame.com/g/601/thumbnail.jpg',
    short_description: 'A free-to-play team-based tactical shooter.',
    game_url: 'https://www.freetogame.com/open/delta-force',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'TiMi Studio Group',
    developer: 'Team Jade',
    release_date: '2024-12-04',
    freetogame_profile_url: 'https://www.freetogame.com/delta-force',
  },
  {
    id: 597,
    title: 'Strinova',
    thumbnail: 'https://www.freetogame.com/g/597/thumbnail.jpg',
    short_description:
      'A third-person tactical shooter that features the unique mechanic of allowing players to switch between three-dimensional and two-dimensional forms.',
    game_url: 'https://www.freetogame.com/open/strinova',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'iDreamSky',
    developer: 'iDreamSky',
    release_date: '2024-11-21',
    freetogame_profile_url: 'https://www.freetogame.com/strinova',
  },
  {
    id: 598,
    title: 'SUPERVIVE',
    thumbnail: 'https://www.freetogame.com/g/598/thumbnail.jpg',
    short_description:
      'Combine MOBAs, battle royales, and hero shooters into one fast paced game hand you have SUPERVIVE.',
    game_url: 'https://www.freetogame.com/open/supervive',
    genre: 'MOBA',
    platform: 'PC (Windows)',
    publisher: 'Theorycraft Games',
    developer: 'Theorycraft Games',
    release_date: '2024-11-20',
    freetogame_profile_url: 'https://www.freetogame.com/supervive',
  },
  {
    id: 592,
    title: 'Starborne: Frontiers',
    thumbnail: 'https://www.freetogame.com/g/592/thumbnail.jpg',
    short_description: 'A tactical autobattler set 400 years in the future.',
    game_url: 'https://www.freetogame.com/open/starborne-frontiers',
    genre: 'Strategy',
    platform: 'PC (Windows)',
    publisher: 'Solid Clouds hf.',
    developer: 'Solid Clouds hf.',
    release_date: '2024-10-14',
    freetogame_profile_url: 'https://www.freetogame.com/starborne-frontiers',
  },
  {
    id: 593,
    title: 'Return Alive',
    thumbnail: 'https://www.freetogame.com/g/593/thumbnail.jpg',
    short_description: 'A free-to-play top-down tactical shooter.',
    game_url: 'https://www.freetogame.com/open/return-alive',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'KOG',
    developer: 'KOG',
    release_date: '2024-10-23',
    freetogame_profile_url: 'https://www.freetogame.com/return-alive',
  },
  {
    id: 587,
    title: 'Spectre Divide',
    thumbnail: 'https://www.freetogame.com/g/587/thumbnail.jpg',
    short_description:
      'A 3v3 tactical shooter developed and published by Mountaintop Studios in partnership with former pro gamer shroud,',
    game_url: 'https://www.freetogame.com/open/spectre-divide',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Mountaintop Studios',
    developer: 'Mountaintop Studios',
    release_date: '2024-09-03',
    freetogame_profile_url: 'https://www.freetogame.com/spectre-divide',
  },
  {
    id: 588,
    title: 'Vigor',
    thumbnail: 'https://www.freetogame.com/g/588/thumbnail.jpg',
    short_description:
      'A free-to-play looter shooter from the developers of Operation Flashpoint and the Arma series.',
    game_url: 'https://www.freetogame.com/open/vigor',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Bohemia Interactive ',
    developer: 'Bohemia Interactive',
    release_date: '2024-09-18',
    freetogame_profile_url: 'https://www.freetogame.com/vigor',
  },
  {
    id: 602,
    title: 'Smite 2',
    thumbnail: 'https://www.freetogame.com/g/602/thumbnail.jpg',
    short_description:
      'The free-to-play Unreal Engine 5-powered sequel to the popular third-person MOBA',
    game_url: 'https://www.freetogame.com/open/smite-2',
    genre: 'MOBA',
    platform: 'PC (Windows)',
    publisher: 'Hi-Rez Studios',
    developer: 'Titan Forge Games',
    release_date: '2024-08-27',
    freetogame_profile_url: 'https://www.freetogame.com/smite-2',
  },
  {
    id: 583,
    title: 'The First Descendant',
    thumbnail: 'https://www.freetogame.com/g/583/thumbnail.jpg',
    short_description:
      'A free-to-play third-person co-op looter shooter developed and published by Nexon.',
    game_url: 'https://www.freetogame.com/open/the-first-descendant',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Nexon',
    developer: 'Nexon Games Co., Ltd.',
    release_date: '2024-07-02',
    freetogame_profile_url: 'https://www.freetogame.com/the-first-descendant',
  },
];

export const actualGames = gamesInitial.map(
  ({
    developer,
    genre,
    publisher,
    title,
    release_date,
    short_description,
  }) => ({
    developer: developer || 'Разработчик не указан',
    genre: genre || 'Жанр не указан',
    publisher: publisher || 'Издатель не указан',
    title: title || 'Название отсутствует',
    releaseDate: release_date || '01.01.2000',
    shortDescription: short_description || 'Описание отсутствует',
  })
);

async function seed() {
  await db.insert(games).values(actualGames).then(res => console.log(res));
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
