import type { Metadata } from 'next';
import { Blinker, Geist } from 'next/font/google';
import './globals.css';
import { cn } from '@/shared/lib';
import { Preheader } from '@/widgets/Preheader/ui/Preheader';
import { Header } from '@/widgets/Header/ui/Header';

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

const blinkerSans = Blinker({
  variable: '--font-blinker-sans',
  weight: ['400', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: 'Games Store',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="ru"
      className={cn(
        'h-full',
        'antialiased',
        blinkerSans.variable,
        'font-sans',
        geist.variable
      )}
    >
      <body className="flex min-h-full flex-col">
        <Preheader />
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
